In [1]:
import pandas as pd
import numpy as np

In [2]:
name = "Tweets_USA.csv"
dataset = pd.read_csv(f"./datasets/{name}")

In [3]:
dataset.head()

,Unnamed: 0,Unnamed: 0.1,Tweet Id,Date,Hour,User Name,Nickname,Bio,Tweet content,Favs,...,Latitude,Longitude,Country,Place (as appears on Bio),Profile picture,Followers,Following,Listed,Tweet language (ISO 639-1),Tweet Url
0,0,0,721318437075685382,2016-04-16,12:44,Bill Schulhoff,BillSchulhoff,"Husband,Dad,GrandDad,Ordained Minister, Umpire...","Wind 3.2 mph NNE. Barometer 30.20 in, Rising s...",NaN,...,40.760278,-72.954722,US,"East Patchogue, NY",http://pbs.twimg.com/profile_images/3788000007...,386.0,705.0,24.0,en,http://www.twitter.com/BillSchulhoff/status/72...
1,1,1,721318436173979648,2016-04-16,12:44,Daniele Polis,danipolis,"Viagens, geek, moda, batons laranja, cabelos c...",Pausa pro café antes de embarcar no próximo vô...,NaN,...,32.898349,-97.039196,US,"Grapevine, TX",http://pbs.twimg.com/profile_images/7041760340...,812.0,647.0,16.0,pt,http://www.twitter.com/danipolis/status/721318...
2,2,2,721318434169102336,2016-04-16,12:44,Kasey Jacobs,KJacobs27,Norwich University Class of 2017,Good. Morning. #morning #Saturday #diner #VT #...,NaN,...,44.199476,-72.504173,US,"Barre, VT",http://pbs.twimg.com/profile_images/7169585649...,179.0,206.0,2.0,en,http://www.twitter.com/KJacobs27/status/721318...
3,3,3,721318429844582400,2016-04-16,12:44,Stan Curtis,stncurtis,"transcendental music, art for art's sake, craf...",@gratefuldead recordstoredayus 🌹🌹🌹 @ TOMS MUSI...,NaN,...,39.901474,-76.606817,US,"Red Lion, PA",http://pbs.twimg.com/profile_images/6962528246...,1229.0,2071.0,11.0,en,http://www.twitter.com/stncurtis/status/721318...
4,4,4,721318429081407488,2016-04-16,12:44,Dave Borzymowski,wi_borzo,When in doubt....Panic.,Egg in a muffin!!! (@ Rocket Baby Bakery - @ro...,NaN,...,43.060849,-87.998309,US,"Wauwatosa, WI",http://pbs.twimg.com/profile_images/6595279129...,129.0,833.0,9.0,en,http://www.twitter.com/wi_borzo/status/7213184...

In [4]:
dataset.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Tweet Id', 'Date', 'Hour', 'User Name',
       'Nickname', 'Bio', 'Tweet content', 'Favs', 'RTs', 'Latitude',
       'Longitude', 'Country', 'Place (as appears on Bio)', 'Profile picture',
       'Followers', 'Following', 'Listed', 'Tweet language (ISO 639-1)',
       'Tweet Url'],
      dtype='object')

In [5]:
to_drop = ['Tweet Id', 'Date', 'Hour', 'User Name', 'Nickname', 'Bio', 'Favs', 'RTs', 'Country',
           'Place (as appears on Bio)', 'Profile picture', 'Followers',
           'Following', 'Listed', 'Tweet language (ISO 639-1)', 'Tweet Url']
dataset = dataset.drop(to_drop, axis=1)
dataset.head()

,Unnamed: 0,Unnamed: 0.1,Tweet content,Latitude,Longitude
0,0,0,"Wind 3.2 mph NNE. Barometer 30.20 in, Rising s...",40.760278,-72.954722
1,1,1,Pausa pro café antes de embarcar no próximo vô...,32.898349,-97.039196
2,2,2,Good. Morning. #morning #Saturday #diner #VT #...,44.199476,-72.504173
3,3,3,@gratefuldead recordstoredayus 🌹🌹🌹 @ TOMS MUSI...,39.901474,-76.606817
4,4,4,Egg in a muffin!!! (@ Rocket Baby Bakery - @ro...,43.060849,-87.998309

In [6]:
dataset.to_csv(f"./datasets/{name}")
dataset.loc[np.random.permutation(np.array(dataset.index))[:1000]].to_csv(f"./datasets_samples/{name}")